### ISSUE TITLE
Ajouter beaucoup d'adversaires.

### ISSUE THREAD

**Issue by malavv** [malavv/UchihaIncident#13]

**Comment by gadgetsan** [comment]
J'en ai ajouté quelque uns (8) j'ai utilisé un generateur de nom pour les créé, Idealement p-e qu'on pourrais faire un programme qui genere automatiquement une liste d'adversaire...

**Comment by malavv** [comment]
We need moar. Surtout le fait qu'on est rendu des maîtres ninja alors, ils sont quand même facile.
